name: ci-cd (develop)

on:
  pull_request:
    branches: [develop]
    types: [opened, synchronize, reopened]

jobs:
  check-test:
    # The type of runner that the job will run on
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]

    # Select environment. Github Settings -> Environments
    # environment:
    #   name: develop

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Check diff
        id: diff-check
        # when commits are pushed into pull requests
        if: github.event.action == 'synchronize'
        run: echo "diff-count=$(git diff ${{ github.event.before }} ${{ github.event.after }} --name-only --relative=sources | wc -l)" >> $GITHUB_OUTPUT
      - name: Check No diff
        id: no-diff-check
        if: github.event.action != 'synchronize'
        run: echo "diff-count=1" >> $GITHUB_OUTPUT
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: npm install, build and test
        env:
          UNDEFINED_ENV: ${{ secrets.UNDEFINED_ENV }}
        run: |
          npm install
          npm run build
          npm run test
      # - uses: actions/github-script@v6
      #   if: steps.diff-check.outputs.diff-count > 0
      #   run: |
      #     npm install
      #     npm run build
      #     npm run test
