name: ci-cd (develop)

on:
  pull_request:
    branches: [develop]
    types: [opened, synchronize, reopened]

jobs:
  check-test:
    # The type of runner that the job will run on
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]

    # Select environment. Github Settings -> Environments
    # environment:
    #   name: develop

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Get changed target files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            **/*.test.{ts,js}
            ./src/app.{ts,js}
      - name: List all changed files
        if: github.event_name == 'pull_request'
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Changed file: $file"
          done

      # here
      # - name: Check diff
      #   id: diff-check
      #   # when commits are pushed into pull requests
      #   if: github.event.action == 'synchronize' || github.event.action == 'opened'
      #   run: echo "diff-count=$(git diff ${{ github.event.before }} ${{ github.event.after }} --name-only --relative=sources | wc -l)" >> $GITHUB_OUTPUT
      # - name: Check No diff
      #   id: no-diff-check
      #   if: github.event.action != 'synchronize' && github.event.action != 'opened'
      #   run: echo "diff-count=1" >> $GITHUB_OUTPUT
      # here

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: npm install, build and test
        env:
          UNDEFINED_ENV: ${{ secrets.UNDEFINED_ENV }}
        run: |
          npm install
          npm run build
          npm run test
      - name: build or test depending on the changed file
        if: github.event_name == 'pull_request'
        run: |
          for changed_file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Changed file name is ${changed_file}."
            if [[ "$changed_file" == *".test."* ]]; then
              echo "${changed_file} has been changed."
              npm run test
            elif [[ "$changed_file" == "src/app.ts" ]]; then
              echo "${changed_file} has been changed."
              npm run build
            else
              echo "${changed_file} has been changed but process is skipped."
              npm i
            fi  
          done

      # - uses: actions/github-script@v6
      #   if: steps.diff-check.outputs.diff-count > 0
      #   run: |
      #     npm install
      #     npm run build
      #     npm run test
